### PR TITLE
Create CR and CRD boilerplates for WebAssembly

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by tabatkins** [comment]
(I'm holding off on merging this for now, since it looks like you're asking for approval. lmk when it's merge-ready)

**Comment by dschuff** [comment]
Yeah, thanks, I would like to get @sideshowbarker's OK that this is heading in the right direction.
It may take some more tweaks to get it past echidna's validation, but those could also be followup PRs.

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Looks great to me

> (I'm holding off on merging this for now, since it looks like you're asking for approval. lmk when it's merge-ready)

Ready to go now

>  It may take some more tweaks to get it past echidna's validation, but those could also be followup PRs.

Yeah, in general that’s usually how it needs to be done

**Pull request merged**
